import argparse
from pathlib import Path

from cihub.commands.docs import cmd_docs
from cihub.cli import CommandResult


def test_docs_generate_writes_files(tmp_path: Path) -> None:
    args = argparse.Namespace(
        subcommand="generate",
        output=str(tmp_path),
        check=False,
        json=True,
    )
    result = cmd_docs(args)
    assert isinstance(result, CommandResult)
    assert result.exit_code == 0

    cli_path = tmp_path / "CLI.md"
    config_path = tmp_path / "CONFIG.md"
    assert cli_path.exists()
    assert config_path.exists()
    assert "Generated by `cihub docs generate`" in cli_path.read_text(
        encoding="utf-8"
    )


def test_docs_check_ok(tmp_path: Path) -> None:
    generate_args = argparse.Namespace(
        subcommand="generate",
        output=str(tmp_path),
        check=False,
        json=True,
    )
    cmd_docs(generate_args)

    check_args = argparse.Namespace(
        subcommand="check",
        output=str(tmp_path),
        json=True,
    )
    result = cmd_docs(check_args)
    assert isinstance(result, CommandResult)
    assert result.exit_code == 0


def test_docs_check_detects_drift(tmp_path: Path) -> None:
    generate_args = argparse.Namespace(
        subcommand="generate",
        output=str(tmp_path),
        check=False,
        json=True,
    )
    cmd_docs(generate_args)

    (tmp_path / "CLI.md").write_text("corrupted", encoding="utf-8")

    check_args = argparse.Namespace(
        subcommand="check",
        output=str(tmp_path),
        json=True,
    )
    result = cmd_docs(check_args)
    assert isinstance(result, CommandResult)
    assert result.exit_code == 1
